name: Move Files and Deploy

on:
  workflow_dispatch:

jobs:
  move-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Move files to correct location
        run: |
          mv client/index.html client/src/index.html
          mv client/404.html client/src/404.html
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Move HTML files to src directory"
          git push

      - name: Build and Deploy
        run: |
          npm install
          npm run build
          npm run deploy
